compilers::
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      fflags: -Mfreeform
    modules: []
    operating_system: rhel8
    paths:
      cc: /usr/tce/packages/rocmcc-tce/rocmcc-4.5.2/bin/amdclang
      cxx: /usr/tce/packages/rocmcc-tce/rocmcc-4.5.2/bin/hipcc
      f77: /usr/tce/packages/rocmcc-tce/rocmcc-4.5.2/bin/amdflang
      fc: /usr/tce/packages/rocmcc-tce/rocmcc-4.5.2/bin/amdflang
    spec: clang@13.0.0_hip
    target: x86_64 